### ISSUE TITLE
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

### ISSUE THREAD

**Issue by Archan2607** [mravanelli/SincNet#50]
I got this error after 1st epoch. Please help I am confused here.

Thanks in advance

Archan

**Comment by mravanelli** [comment]
Hi Archan,
at which line of which function you had this error?

Mirco

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Archan2607** [comment]
Hi

Thanks for replying

Following function got me error.

Epoch 00001: saving model to result/checkpoints/SincNet.hdf5
Valuating test set...
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    model.fit_generator(train_generator, steps_per_epoch=N_batches, epochs=N_epochs, verbose=1, callbacks=callbacks)
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.6/dist-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "train.py", line 59, in on_epoch_end
    val.validate(epoch)
  File "/home/archan/Desktop/new/keras-sincnet/test.py", line 55, in validate
    lab= np.zeros(N_fr + 1) + lab_batch
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')


PS: I was implementing it in keras.

Thanks 
Archan

**Comment by mravanelli** [comment]
I'm not sure about this error. It seems Keras specific. Have you finally solved it?
