### ISSUE TITLE
Error while generating .npy file

### ISSUE THREAD

**Issue by bsshruthi22** [mravanelli/SincNet#85]
Hi,
We are using TIMIT corpus to run SincNet. While generating TIMIT_labels.npy file, we are getting errors

Traceback (most recent call last):
  File "test.py", line 11, in <module>
a=open("labels.txt" ,'r')  # labels.txt contains labels of form sentence id:speaker id ( {'TRAIN/DR5/FJXM0/SX311.WAV': 267,....}
    np.save("TIMIT_labels",a)
  File "/home/iiit_admin/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 536, in save
    pickle_kwargs=pickle_kwargs)
  File "/home/iiit_admin/.local/lib/python3.6/site-packages/numpy/lib/format.py", line 629, in write_array
    pickle.dump(array, fp, protocol=2, **pickle_kwargs)
**TypeError: cannot serialize '_io.TextIOWrapper' object**

Please let us know how to resolve this issue.

**Comment by GefeiYang** [comment]
lower case for your path
