### ISSUE TITLE
The error when run speaker_id.py 

### ISSUE THREAD

**Issue by BLack-yzf** [mravanelli/SincNet#86]
1. hello，Mr.mravanelli
  I have run the speaker_id.py, but i got this error. I have checked the code in line 52. I have found that  one of the signal's "snt_len" in the batchsize  is “2470” ,therefore the value of "snt_len-2*wlen" is negtive which causes this error.  I look forward to your answer and thank you very much!

Traceback (most recent call last):
  File "speaker_id.py", line 235, in <module>
    [inp,lab]=create_batches_rnd(batch_size,data_folder,wav_lst_tr,snt_tr,wlen,lab_dict,0.2)
  File "speaker_id.py", line 52, in create_batches_rnd
    snt_beg=np.random.randint(snt_len-2*wlen) #randint(0, snt_len-2*wlen-1)##
  File "mtrand.pyx", line 745, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1363, in numpy.random._bounded_integers._rand_int32
ValueError: low >= high

**Comment by BLack-yzf** [comment]
I found more details. Is there any chance the prepared data is not exactly right? Hope you can reply. Thanks.
train/dr5/fbjl0/sx202.wav    14940
train/dr5/mmdm1/sx333.wav    56333
train/dr4/mtrc0/sx93.wav    20220
train/dr5/mmab1/sx414.wav    36862
train/dr8/mbcg0/sx327.wav    60940
train/dr1/fsma0/sx361.wav    33339
train/dr5/flmk0/sx315.wav    35970
train/dr4/fjxp0/sx42.wav    25120
train/dr2/msat0/sx446.wav    2470
